USE [master]
GO

/****** Object:  Database [utptwManagementSystem ]    Script Date: 7/12/2021 2:49:54 PM ******/
CREATE DATABASE [utptwManagementSystem ]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'utptwManagementSystem', FILENAME = N'C:\Users\aihristov18\utptwManagementSystem .mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'utptwManagementSystem _log', FILENAME = N'C:\Users\aihristov18\utptwManagementSystem _log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [utptwManagementSystem ].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [utptwManagementSystem ] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [utptwManagementSystem ] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [utptwManagementSystem ] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [utptwManagementSystem ] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [utptwManagementSystem ] SET ARITHABORT OFF 
GO

ALTER DATABASE [utptwManagementSystem ] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [utptwManagementSystem ] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [utptwManagementSystem ] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [utptwManagementSystem ] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [utptwManagementSystem ] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [utptwManagementSystem ] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [utptwManagementSystem ] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [utptwManagementSystem ] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [utptwManagementSystem ] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [utptwManagementSystem ] SET  DISABLE_BROKER 
GO

ALTER DATABASE [utptwManagementSystem ] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [utptwManagementSystem ] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [utptwManagementSystem ] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [utptwManagementSystem ] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [utptwManagementSystem ] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [utptwManagementSystem ] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [utptwManagementSystem ] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [utptwManagementSystem ] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [utptwManagementSystem ] SET  MULTI_USER 
GO

ALTER DATABASE [utptwManagementSystem ] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [utptwManagementSystem ] SET DB_CHAINING OFF 
GO

ALTER DATABASE [utptwManagementSystem ] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [utptwManagementSystem ] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [utptwManagementSystem ] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [utptwManagementSystem ] SET QUERY_STORE = OFF
GO

USE [utptwManagementSystem ]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [utptwManagementSystem ] SET  READ_WRITE 
GO


